version: "3.9"

services:
  web:
    build:
      context: ./Backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
    environment:
      - VITE_APP_BACKEND_ADDRESS=http://web:8000/api
    networks:
      - app-network

networks:
  app-network: